runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "todomvc-bc"

handlers:
- url: /
  static_files: dist/todomvc-app/index.html
  upload: dist/todomvc-app/index.html

- url: /
  static_dir: dist/todomvc-app
